# Generated by Django 5.1.4 on 2025-05-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='vegeterian',
            field=models.BooleanField(default=False),
        ),
    ]
